### ISSUE TITLE
サインアウト時にhomeなどが見れてしまう

### ISSUE THREAD

**Issue by n4mlz** [Nameless-itf23/SimpleAuth#7]
# 概要
サインアウト時は `PageTransition.tsx` の `getPermissionLevel()` の返り値がundefinedになり、これに対する処理が作られていない

# タスク
`Page Transition.tsx` 内の処理を確認する

**Comment by Nameless-itf23** [comment]
done

**Comment by n4mlz** [comment]
done!

## 原因
`getPermissionLevel()` 内で `user == undefined` としていたため、 `null == undefined` が true になってしまっていた。 `user === undefined` とすることで修正。
